vim.opt.foldmethod = "syntax"
vim.opt.foldlevelstart=-1
vim.opt.foldnestmax=2
vim.opt.exrc = true
vim.opt.secure = true
vim.opt.relativenumber = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.hidden = true
vim.opt.errorbells = false
vim.opt.tabstop = 4
vim.opt.softtabstop = 0
vim.opt.shiftwidth = 4
vim.opt.expandtab = false
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.number = true
vim.opt.wrap = true
vim.opt.linebreak = true
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.writebackup = false
vim.opt.undofile = false
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 4
vim.opt.sidescrolloff = 4
vim.opt.showmode = true
vim.opt.showcmd = true
vim.opt.signcolumn = "yes" --"auto"
vim.opt.cmdheight = 1
vim.opt.timeout = true
vim.opt.timeoutlen = 3000
vim.opt.ttimeoutlen = 10
vim.opt.encoding = "utf-8"
vim.opt.backspace = { "indent", "eol", "start" }
vim.opt.history = 200
vim.opt.ruler = true
vim.opt.laststatus = 2
--vim.opt.colorcolumn = { 80 }
vim.opt.wildmenu = true
vim.opt.paste = false
vim.opt.autoread = true
vim.opt.mouse = "a"
vim.opt.list = true
--vim.opt.listchars = "nbsp:×,tab:•\ ,trail:•,extends:»,precedes:"
vim.opt.background = "dark"
vim.opt.sessionoptions = "blank,buffers,folds,help,tabpages,winsize,terminal,sesdir"
vim.opt.cursorline = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.shortmess:append "c"
-- vim.opt.showtabline = 2
